version = 0.1
[default.pipeline_bootstrap.parameters]
oidc_provider_url = "https://token.actions.githubusercontent.com"
oidc_client_id = "sts.amazonaws.com"
github_org = "jcmc1"
github_repo = "sam-java-lambda"
deployment_branch = "main"
oidc_provider = "github-actions"
permissions_provider = "OpenID Connect (OIDC)"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "y"
cloudformation_execution_role = "y"
artifacts_bucket = ""
image_repository = ""
region = "us-east-1"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "y"
cloudformation_execution_role = "y"
artifacts_bucket = ""
image_repository = ""
region = "us-east-1"
